### ISSUE TITLE
Simplify input datasets in CLI

### ISSUE THREAD

**Issue by a-slide** [tleonardi/nanocompore#57]
What do you think of having an imput YAML file instead of the 4 options required at the moment ?

```
sample1:
    rep1:   path/to/sample1/rep1/data
    rep2:   path/to/sample1/rep2/data
sample2:
    rep1:   path/to/sample2/rep1/data
    rep2:   path/to/sample2/rep2/data
```
It would be parsed directly as required by nanocompore
